#!/usr/bin/env bash
# Usage: script/make [--no-update]
#
# Builds gh without downloading any dependency. With `--no-update`, builds it with autoupdate disabled.
#
# Author: Jingwen Owen Ou

set -e

BUILD_DIR=`mktemp -d -t gh`
GODEPPATH=`pwd`/Godeps/_workspace
GHSOURCE=$BUILD_DIR/src/github.com/jingweno/gh

export GOPATH=$BUILD_DIR:$GODEPPATH

mkdir -p $GHSOURCE
cp -R `pwd`/. $GHSOURCE

case "$1" in
  "" )
    go build -o gh
    ;;
  --no-update )
    go build -o gh --tags noupdate
    ;;
  -h | --help )
    sed -ne '/^#/!q;s/.\{1,2\}//;1d;p' < "$0"
    exit
    ;;
  * )
    "$0" --help >&2
    exit 1
esac

