#!/usr/bin/env bash
# Usage: make
#
# Package gh for release
#
# Author: Jingwen Owen Ou

GOPACK_PATH="`pwd`/.gopack/vendor"

rm -f $GOPACK_PATH/src/github.com/jingweno/gh
GOPATH="$GOPACK_PATH:$GOPATH" gotask package
