#!/usr/bin/env bash
# Usage: build
#
# Run go test with gopack
#
# Author: Jingwen Owen Ou

go get code.google.com/p/go.tools/cmd/cover
go fmt ./...
GOPATH="`pwd`/.gopack/vendor" go test -cover -v ./...
